---
- name: Deploy node_exporter
  hosts: service_instances
  remote_user: ubuntu
  roles:
    - cloudalchemy.node_exporter
    - cloudalchemy.blackbox-exporter
  tags:
    - node_exporter

- name: Setup prometheus and alert manager
  hosts: prometheus
  remote_user: root
  roles:
    - cloudalchemy.prometheus
    - cloudalchemy.alertmanager
  tags:
    - prometheus

- name: Deploy grafana
  hosts: grafana
  remote_user: root
  roles:
    - cloudalchemy.grafana
  tags:
    - grafana